from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict

import yaml


def load_galaxy_singularity(path: Path) -> dict:
    """
    Load a json with galaxy singularity container entries from the CVMFS

    This function assumes the cache was generated by build_cache.py
    and does not attempt to rebuild or validate it.

    Each entry has fields entry_name, tool_name, tag, path, size_bytes, mtime.

    This is used as a ground truth of what exists in the CVMFS repository at the time of caching.

    Rebuild the cache/snapshot periodically or as required to fetcht the latest updates.
    """
    if not path.exists():
        raise FileNotFoundError(f"Cache file not found: {path}")

    with path.open("r", encoding="utf-8") as f:
        data: Dict[str, Any] = json.load(f)

    if isinstance(data, dict):
        entries = data.get("entries")
        if isinstance(entries, list):
            tool_map: Dict[str, list] = {}
            for entry in entries:
                if not isinstance(entry, dict):
                    continue
                tool_name = entry.get("tool_name")
                if not tool_name:
                    continue
                tool_map.setdefault(tool_name, []).append(entry)
            return tool_map
        return data

    if isinstance(data, list):
        tool_map: Dict[str, list] = {}
        for entry in data:
            if not isinstance(entry, dict):
                continue
            tool_name = entry.get("tool_name")
            if not tool_name:
                continue
            tool_map.setdefault(tool_name, []).append(entry)
        return tool_map

    return data


def load_biotools(path: Path) -> dict:
    """
    Load a yaml that contains metadata from https://github.com/AustralianBioCommons/finder-service-metadata/tree/main/data

    This will be used as the ground truth for tool/container metadata.
    """
    if not path.exists():
        raise FileNotFoundError(f"Cache file not found: {path}")

    with path.open("r", encoding="utf-8") as f:
        data: Any = yaml.safe_load(f)

    # Reformat so each key is the tool id
    if isinstance(data, list):
        return {entry["id"]: entry for entry in data if "id" in entry}

    if isinstance(data, dict):
        return data

    return {}
